### ISSUE TITLE
Roadmap ideas

### ISSUE THREAD

**Issue by zachsa** [SAEON/mnemosyne#17]
- [ ] Logging/metrics: log range requests
- [ ] More expressive permissions model, allowing for update/delete/post granularity
- [ ] A drag/drop website creator for creating and serving static sites?
- [ ] URL rewriting - Similar to couchDB, allows for 'top level' websites whenever an index.html file is present in a folder
